name: live_mix_master
description: Live audio routing, meter, recording, fingerprinting and broadcast console.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  ffi: 2.1.3
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  licenses:
    - assets/fonts/LICENSES.md
  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Variable.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Variable.ttf
