import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

enum PcmBitDepth { pcm16Bit(16, 2), pcm24Bit(24, 3), pcm32BitFloat(32, 4); const PcmBitDepth(this.bitDepth, this.bytesPerSample); final int bitDepth; final int bytesPerSample; }
class RecordingConfig { const RecordingConfig({required this.destinationDirectory, this.sessionPrefix = 'LMM_SESSION', this.sampleRate = 48000, this.channels = 2, this.bitDepth = PcmBitDepth.pcm24Bit, this.flushThresholdBytes = 65536}); final String destinationDirectory, sessionPrefix; final int sampleRate, channels, flushThresholdBytes; final PcmBitDepth bitDepth; }
class RecordingStats { const RecordingStats({required this.totalBytesWritten, required this.elapsed, required this.filePath, required this.currentFileSizeMb}); final int totalBytesWritten; final Duration elapsed; final String filePath; final double currentFileSizeMb; }
class LosslessRecordingWriter {
  LosslessRecordingWriter({required this.config}); final RecordingConfig config; final _events = StreamController<RecordingStats>.broadcast(); final _buffer = BytesBuilder(copy: false); RandomAccessFile? _file; String? _path; DateTime? _started; int _bytes = 0; Timer? _timer;
  Stream<RecordingStats> get onStatsUpdated => _events.stream; bool get isRecording => _file != null; String? get currentFilePath => _path;
  Future<String> startRecording() async { if (isRecording) throw StateError('Recording is already in progress.'); final dir = Directory(config.destinationDirectory); if (!await dir.exists()) await dir.create(recursive: true); _path = '${dir.path}/${config.sessionPrefix}_${DateTime.now().millisecondsSinceEpoch}.wav'; _file = await File(_path!).open(mode: FileMode.write); _started = DateTime.now(); _bytes = 0; await _file!.writeFrom(_header(0)); _timer = Timer.periodic(const Duration(seconds: 1), (_) => _emit()); _emit(); return _path!; }
  void writeStereoSamples(Float32List samples) { if (!isRecording) return; _buffer.add(_encode(samples)); if (_buffer.length >= config.flushThresholdBytes) _flush(); }
  void _flush() { if (!isRecording || _buffer.isEmpty) return; final bytes = _buffer.takeBytes(); _file!.writeFromSync(bytes); _bytes += bytes.length; }
  Future<RecordingStats> stopRecording() async { if (!isRecording) throw StateError('Cannot stop a recording that is not active.'); _timer?.cancel(); _flush(); await _file!.setPosition(0); await _file!.writeFrom(_header(_bytes)); await _file!.flush(); await _file!.close(); _file = null; final stats = _stats(); _started = null; _emit(stats); return stats; }
  Future<void> dispose() async { if (isRecording) await stopRecording(); await _events.close(); }
  RecordingStats _stats() => RecordingStats(totalBytesWritten: _bytes + 44, elapsed: _started == null ? Duration.zero : DateTime.now().difference(_started!), filePath: _path ?? '', currentFileSizeMb: (_bytes + 44) / 1048576);
  void _emit([RecordingStats? stats]) { if (_path != null && !_events.isClosed) _events.add(stats ?? _stats()); }
  Uint8List _encode(Float32List input) { final out = Uint8List(input.length * config.bitDepth.bytesPerSample); final data = ByteData.sublistView(out); for (var i = 0; i < input.length; i++) { final value = input[i].clamp(-1.0, 1.0).toDouble(); final offset = i * config.bitDepth.bytesPerSample; if (config.bitDepth == PcmBitDepth.pcm16Bit) data.setInt16(offset, (value * 32767).round(), Endian.little); else if (config.bitDepth == PcmBitDepth.pcm24Bit) { final sample = (value * 8388607).round(); out[offset] = sample & 255; out[offset + 1] = (sample >> 8) & 255; out[offset + 2] = (sample >> 16) & 255; } else { data.setFloat32(offset, value, Endian.little); } } return out; }
  Uint8List _header(int length) { final out = Uint8List(44); final data = ByteData.sublistView(out); out.setRange(0, 4, [82,73,70,70]); data.setUint32(4, length + 36, Endian.little); out.setRange(8, 12, [87,65,86,69]); out.setRange(12, 16, [102,109,116,32]); data.setUint32(16,16,Endian.little); data.setUint16(20, config.bitDepth == PcmBitDepth.pcm32BitFloat ? 3 : 1, Endian.little); data.setUint16(22,config.channels,Endian.little); data.setUint32(24,config.sampleRate,Endian.little); data.setUint32(28,config.sampleRate * config.channels * config.bitDepth.bytesPerSample,Endian.little); data.setUint16(32,config.channels * config.bitDepth.bytesPerSample,Endian.little); data.setUint16(34,config.bitDepth.bitDepth,Endian.little); out.setRange(36,40,[100,97,116,97]); data.setUint32(40,length,Endian.little); return out; }
}
